FROM alpine:latest

RUN apk add --no-cache wget ca-certificates

WORKDIR /app

RUN wget https://github.com/cacggghp/vk-turn-proxy/releases/download/v1.2.3/server-linux-amd64 -O server && \
    chmod +x server

CMD ["/app/server"]